# This file defines the principal settings for this project

REPO_NAME          := Dutch Tracks

BASE_FILENAME       := dutchtracks

# Uncomment those lines which are applicable
USE_NML := 1

# If you want to use gimp to automatically create the png files from
# layered source files (psd or xcf), uncomment the following line and
# create the file and add one line per png file which shall be created:
# png filename <tab> source filename <tab> layer numbers separated by space
# (see also scripts/gimpscript)
# GRAPHICS_SOURCE_LIST_FILES := gfx/png_source_list

# If everything is default, you don't need the rest:
# EXTRA_DEP          :=


# Documentation files:
DOC_FILES = docs/readme.txt docs/license.txt docs/changelog.txt

# file extentions which indicate plain text source files,
# parsable by a text editor
# FILE_SRC_EXTENSIONS = nml pnml tnml
# LANG_EXTENSION      = lng

# file extensions which indicate binary source files
# FILE_INC_EXTENSIONS = wav pcx png

# List of all files which will get shipped
# DOC_FILES = readme, changelog and license
# GRF_FILENAME = MAIN_FILENAME_SRC with the extention .grf
# Add any additional, not usual files here, too, including
# their relative path to the root of the repository
